# Generated by Django 4.2.3 on 2023-10-22 20:53

from django.db import migrations, models
import start_page_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Порядковый номер')),
                ('name', models.CharField(blank=True, max_length=15, null=True, verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to=start_page_app.models.upload_to, verbose_name='Изображение')),
                ('link', models.URLField(verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'ссылка',
                'verbose_name_plural': 'ссылки',
            },
        ),
    ]
